### ISSUE TITLE
No such file - ["config/database.yml"]

### ISSUE THREAD

**Issue by jaryn** [ManageIQ/integration_tests#3916] opened 2017-01-03 22:45 UTC
```git bisect ``` told me that the patch 056e77a75b71bf7eff146e8ea8240deb4b2291cf causes the ```scripts/ipappliance.py configure $CFME_IP```  to fail with

```
scripts/ipappliance.py configure CENSORED
WARNING:psphere.config:Configuration file /home/jhenner/.psphere/config.yaml could not be opened, perhaps you haven't created one?
[2017-01-03 17:08:47] Calling configure(, ) on CENSORED
[2017-01-03 17:08:47] === Starting on CENSORED as thread 0
INFO:cfme:Running command `cat /var/www/miq/vmdb/VERSION`
INFO:cfme:Running rails command `"File.open('/tmp/yam_dump.yaml', 'w') {|f| f.write(Settings.to_hash.deep_stringify_keys.to_yaml) }"`
INFO:cfme:Running command `cd /var/www/miq/vmdb; bin/rails runner "File.open('/tmp/yam_dump.yaml', 'w') {|f| f.write(Settings.to_hash.deep_stringify_keys.to_yaml) }"`
ERROR:cfme:Config couldn't be found
ERROR:cfme:/opt/rh/cfme-gemset/gems/railties-5.0.0.1/lib/rails/application/configuration.rb:143:in `database_configuration': Cannot load `Rails.application.database_configuration`: (RuntimeError)
Could not load database configuration. No such file - ["config/database.yml"]
	from /var/www/miq/vmdb/config/environments/patches/database_configuration.rb:31:in `database_configuration'
	from /opt/rh/cfme-gemset/gems/activerecord-5.0.0.1/lib/active_record/railtie.rb:122:in `block (2 levels) in <class:Railtie>'
	from /opt/rh/cfme-gemset/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
	from /opt/rh/cfme-gemset/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
	from /opt/rh/cfme-gemset/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
	from /opt/rh/cfme-gemset/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:27:in `each'
	from /opt/rh/cfme-gemset/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
	from /opt/rh/cfme-gemset/gems/activerecord-5.0.0.1/lib/active_record/railtie.rb:121:in `block in <class:Railtie>'
	from /opt/rh/cfme-gemset/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /opt/rh/cfme-gemset/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `run'
	from /opt/rh/cfme-gemset/gems/railties-5.0.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /opt/rh/rh-ruby23/root/usr/share/ruby/tsort.rb:228:in `block in tsort_each'
	from /opt/rh/rh-ruby23/root/usr/share/ruby/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /opt/rh/rh-ruby23/root/usr/share/ruby/tsort.rb:431:in `each_strongly_connected_component_from'
	from /opt/rh/rh-ruby23/root/usr/share/ruby/tsort.rb:349:in `block in each_strongly_connected_component'
	from /opt/rh/rh-ruby23/root/usr/share/ruby/tsort.rb:347:in `each'
	from /opt/rh/rh-ruby23/root/usr/share/ruby/tsort.rb:347:in `call'
	from /opt/rh/rh-ruby23/root/usr/share/ruby/tsort.rb:347:in `each_strongly_connected_component'
	from /opt/rh/rh-ruby23/root/usr/share/ruby/tsort.rb:226:in `tsort_each'
	from /opt/rh/rh-ruby23/root/usr/share/ruby/tsort.rb:205:in `tsort_each'
	from /opt/rh/cfme-gemset/gems/railties-5.0.0.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /opt/rh/cfme-gemset/gems/railties-5.0.0.1/lib/rails/application.rb:352:in `initialize!'
	from /opt/rh/cfme-gemset/gems/railties-5.0.0.1/lib/rails/railtie.rb:193:in `public_send'
	from /opt/rh/cfme-gemset/gems/railties-5.0.0.1/lib/rails/railtie.rb:193:in `method_missing'
	from /var/www/miq/vmdb/config/environment.rb:5:in `<top (required)>'
	from /opt/rh/cfme-gemset/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /opt/rh/cfme-gemset/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /opt/rh/cfme-gemset/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /opt/rh/cfme-gemset/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /opt/rh/cfme-gemset/gems/railties-5.0.0.1/lib/rails/application.rb:328:in `require_environment!'
	from /opt/rh/cfme-gemset/gems/railties-5.0.0.1/lib/rails/commands/runner.rb:52:in `<top (required)>'
	from /opt/rh/cfme-gemset/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:138:in `require'
	from /opt/rh/cfme-gemset/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:138:in `require_command!'
	from /opt/rh/cfme-gemset/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:104:in `runner'
	from /opt/rh/cfme-gemset/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /opt/rh/cfme-gemset/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

ERROR:cfme:Error obtaining config
Traceback (most recent call last):
  File "/home/jhenner/work/CMQE_integration_tests/utils/appliance/__init__.py", line 1458, in get_host_address
    server = self.get_yaml_config('vmdb').get('server', None)
  File "/home/jhenner/work/CMQE_integration_tests/utils/appliance/__init__.py", line 1644, in get_yaml_config
    raise Exception('Error obtaining config')
Exception: Error obtaining config
ERROR:cfme:(CENSORED) Exception occured while fetching host address
^C
```

```
cat <<EOF > /tmp/test
set -x
nova rebuild  e43a2259-9c6b-4bbc-85ef-81dc77d2b617 f5f8fc21-52db-45db-8680-02de7dfa2936
while ! ssh root@$CFME_IP "echo ====Ready==="; do echo not yet; sleep 1; done
scripts/ipappliance.py configure $CFME_IP 2>&1 | tee /dev/stderr |  grep -m1 appliance_console_cli
EOF

git bisect start af91a0715 5e424acd34f8
git bisect run bash /tmp/test
```

Is it the order of the operations that the ipappliance do for configuring the CFME bad?

**Comment by psav** [comment] 2017-01-04 00:45
Investigating..., is there a complete traceback?

**Comment by jaryn** [comment] 2017-01-04 03:15
@psav The above is a quite full traceback that you might need. I have just booted the appliance and started bisecting, using the small script in`/tmp/test` which is also above. 

You may need to change the instance and image ids of the nova rebuild.

**Comment by psav** [comment] 2017-01-04 11:00
Yes, I have reproduced the issue. It was the part after that that I needed to see and we have a fix for this in #3918 - Just waiting on PRT to confirm it doens't blow things up and we will merge it.

**Comment by mfalesni** [comment] 2017-01-11 12:23
The abovementioned PR was already merged, closing this issue.

**Closed by mfalesni** 2017-01-11 12:23 UTC

**Comment by movitto** [comment] 2018-01-06 01:06
I'm running into the same issue on the lastest HEAD of the manageiq-ui-classic repo. I suspect the issue is in the underlying dependency, the miq project itself though cannot say for sure. Any insight would be much appreciated

**Comment by mfalesni** [comment] 2018-01-08 10:05
@movitto with our tests?

**Comment by movitto** [comment] 2018-01-08 16:20
@mfalesni I'm not sure if the problem is with these tests or those in the main miq codebase but my procedure is as follows:

- clone manageiq-ui-classic
- run "bundle install" 
- get an error about "manageiq" needing to be under the spec dir
- clone the manageiq project and symlink it to that dir
- run bundle install again (sucessfully)
- attempt to run 'bundle exec rspec' which results in the following error:

```
[mmorsi@localhost manageiq-ui-classic]$ bundle exec rspec
bundler: failed to load command: rspec (/home/mmorsi/bin/rspec)
RuntimeError: Cannot load `Rails.application.database_configuration`:
Could not load database configuration. No such file - ["config/database.yml"]
  /home/mmorsi/.gem/ruby/2.4.0/gems/railties-5.0.6/lib/rails/application/configuration.rb:143:in `database_configuration'
  /home/mmorsi/workspace/cfme/tmp/manageiq/lib/patches/database_configuration_patch.rb:32:in `database_configuration'
  /home/mmorsi/.gem/ruby/2.4.0/gems/activerecord-5.0.6/lib/active_record/railtie.rb:122:in `block (2 levels) in <class:Railtie>'
  /home/mmorsi/.gem/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:69:in `instance_eval'
  /home/mmorsi/.gem/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
  /home/mmorsi/.gem/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
  /home/mmorsi/.gem/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
  /home/mmorsi/.gem/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:41:in `block in on_load'
  /home/mmorsi/.gem/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:40:in `each'
  /home/mmorsi/.gem/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:40:in `on_load'
  /home/mmorsi/.gem/ruby/2.4.0/gems/activerecord-5.0.6/lib/active_record/railtie.rb:121:in `block in <class:Railtie>'
  /home/mmorsi/.gem/ruby/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:30:in `instance_exec'
  /home/mmorsi/.gem/ruby/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:30:in `run'
  /home/mmorsi/.gem/ruby/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/share/ruby/tsort.rb:228:in `block in tsort_each'
  /usr/share/ruby/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/share/ruby/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/share/ruby/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/share/ruby/tsort.rb:347:in `each'
  /usr/share/ruby/tsort.rb:347:in `call'
  /usr/share/ruby/tsort.rb:347:in `each_strongly_connected_component'
  /usr/share/ruby/tsort.rb:226:in `tsort_each'
  /usr/share/ruby/tsort.rb:205:in `tsort_each'
  /home/mmorsi/.gem/ruby/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:54:in `run_initializers'
  /home/mmorsi/.gem/ruby/2.4.0/gems/railties-5.0.6/lib/rails/application.rb:352:in `initialize!'
  /home/mmorsi/.gem/ruby/2.4.0/gems/railties-5.0.6/lib/rails/railtie.rb:193:in `public_send'
  /home/mmorsi/.gem/ruby/2.4.0/gems/railties-5.0.6/lib/rails/railtie.rb:193:in `method_missing'
  /home/mmorsi/workspace/cfme/tmp/manageiq-ui-classic/spec/manageiq/config/environment.rb:5:in `<top (required)>'
  /home/mmorsi/workspace/cfme/tmp/manageiq-ui-classic/spec/manageiq/spec/spec_helper.rb:9:in `require'
  /home/mmorsi/workspace/cfme/tmp/manageiq-ui-classic/spec/manageiq/spec/spec_helper.rb:9:in `<top (required)>'
  /home/mmorsi/.gem/ruby/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1453:in `require'
  /home/mmorsi/.gem/ruby/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1453:in `block in requires='
  /home/mmorsi/.gem/ruby/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1453:in `each'
  /home/mmorsi/.gem/ruby/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1453:in `requires='
  /home/mmorsi/.gem/ruby/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
  /home/mmorsi/.gem/ruby/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration_options.rb:111:in `each'
  /home/mmorsi/.gem/ruby/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
  /home/mmorsi/.gem/ruby/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration_options.rb:21:in `configure'
  /home/mmorsi/.gem/ruby/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:99:in `setup'
  /home/mmorsi/.gem/ruby/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:86:in `run'
  /home/mmorsi/.gem/ruby/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:71:in `run'
  /home/mmorsi/.gem/ruby/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:45:in `invoke'
  /home/mmorsi/.gem/ruby/2.4.0/gems/rspec-core-3.6.0/exe/rspec:4:in `<top (required)>'
  /home/mmorsi/bin/rspec:23:in `load'
  /home/mmorsi/bin/rspec:23:in `<top (required)>'
```

This is on my local dev env. Attempting this on the appliance (linking our vendored miq app to the manageiq-ui-classic spec dir) and tweaking the miq settings does seems to allow further proceeding but the process fails due to other rspec failures.

Since the tests worked in my local dev env in the past, it'd be good to be able to resolve this to get it working again, so as to be able to develop and test features against the latest HEAD.

Any thoughts?
