### ISSUE TITLE
view.is_displayed fails during compliance condition creation

### ISSUE THREAD

**Issue by jan-zmeskal** [ManageIQ/integration_tests#8082] opened 2018-11-05 11:51 UTC
I bumped into this with test case `cfme/tests/control/test_actions.py::test_action_prevent_vm_retire`. There is a prerequisite called [compliance condition](https://github.com/ManageIQ/integration_tests/blob/add3ff01840b4d784e0006e23d5e6cbe140a3302/cfme/tests/control/test_actions.py#L208). After the compliance condition is created, framework checks if `ConditionDetailsView` is displayed [here](https://github.com/ManageIQ/integration_tests/blob/add3ff01840b4d784e0006e23d5e6cbe140a3302/cfme/control/explorer/conditions.py#L249). At that point, this error is thrown: https://up1-vrutkovs.int.open.paas.redhat.com/#e2HldZaMoIdNVXhDjCz9PQ

Also, [this](https://up1-vrutkovs.int.open.paas.redhat.com/#oAWwlcXLNgYX3qRv6RzJ2A) occurs during compliance condition's deletion.

**Comment by john-dupuy** [comment] 2018-11-06 12:53
I am seeing a similar issue when for the alert creation in the test:
 `cfme/tests/control/test_alerts.py::test_alert_snmp`. The alert gets created but the assertion that `view.is_displayed` fails.

**Comment by mshriver** [comment] 2018-11-06 21:05
@jan-zmeskal @john-dupuy thanks for the updates!

@john-dupuy your issue is a bit separate, dealing with alerts, though the same behavior. I believe you've fixed this already in your recent PR.

Concerning condition views, @mmojzis has been assigned to this issue, it will impact any tests that rely on condition creations.

**Comment by mshriver** [comment] 2018-11-06 21:06
I'm going to close this issue, as it boils down to a duplicate of #7960  and I would like to continue tracking view failures there.

**Closed by mshriver** 2018-11-06 21:06 UTC
Labels: issue-bug
